BEGIN {
D["PACKAGE_NAME"]=" \"pacemaker\""
D["PACKAGE_TARNAME"]=" \"pacemaker\""
D["PACKAGE_VERSION"]=" \"2.1.4\""
D["PACKAGE_STRING"]=" \"pacemaker 2.1.4\""
D["PACKAGE_BUGREPORT"]=" \"users@clusterlabs.org\""
D["PACKAGE_URL"]=" \"https://ClusterLabs.org/pacemaker/\""
D["PACKAGE"]=" \"pacemaker\""
D["VERSION"]=" \"2.1.4\""
D["ENABLE_VERSIONED_ATTRS"]=" 0"
D["STDC_HEADERS"]=" 1"
D["HAVE_SYS_TYPES_H"]=" 1"
D["HAVE_SYS_STAT_H"]=" 1"
D["HAVE_STDLIB_H"]=" 1"
D["HAVE_STRING_H"]=" 1"
D["HAVE_MEMORY_H"]=" 1"
D["HAVE_STRINGS_H"]=" 1"
D["HAVE_INTTYPES_H"]=" 1"
D["HAVE_STDINT_H"]=" 1"
D["HAVE_UNISTD_H"]=" 1"
D["restrict"]=" __restrict"
D["HAVE_BYTESWAP_H"]=" 1"
D["HAVE_DLFCN_H"]=" 1"
D["LT_OBJDIR"]=" \".libs/\""
D["LT_MODULE_EXT"]=" \".so\""
D["LT_MODULE_PATH_VAR"]=" \"LD_LIBRARY_PATH\""
D["LT_DLSEARCH_PATH"]=" \"/lib:/usr/lib:/usr/lib/x86_64-linux-gnu/libfakeroot:/usr/local/lib/i386-linux-gnu:/lib/i386-linux-gnu:/usr/lib/i386-linux-"\
"gnu:/usr/local/lib/i686-linux-gnu:/lib/i686-linux-gnu:/usr/lib/i686-linux-gnu:/usr/local/lib:/usr/local/lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu:/"\
"usr/lib/x86_64-linux-gnu\""
D["HAVE_LIBDL"]=" 1"
D["HAVE_DLERROR"]=" 1"
D["HAVE_LIBDLLOADER"]=" 1"
D["HAVE_ARGZ_H"]=" 1"
D["HAVE_ERROR_T"]=" 1"
D["HAVE_ARGZ_ADD"]=" 1"
D["HAVE_ARGZ_APPEND"]=" 1"
D["HAVE_ARGZ_COUNT"]=" 1"
D["HAVE_ARGZ_CREATE_SEP"]=" 1"
D["HAVE_ARGZ_INSERT"]=" 1"
D["HAVE_ARGZ_NEXT"]=" 1"
D["HAVE_ARGZ_STRINGIFY"]=" 1"
D["HAVE_WORKING_ARGZ"]=" 1"
D["HAVE_PRELOADED_SYMBOLS"]=" 1"
D["HAVE_LTDL"]=" 1"
D["HAVE_UNISTD_H"]=" 1"
D["HAVE_DIRENT_H"]=" 1"
D["HAVE_CLOSEDIR"]=" 1"
D["HAVE_OPENDIR"]=" 1"
D["HAVE_READDIR"]=" 1"
D["LT_LIBEXT"]=" \"a\""
D["LT_LIBPREFIX"]=" \"lib\""
D["SIZEOF_CHAR"]=" 1"
D["SIZEOF_SHORT"]=" 2"
D["SIZEOF_INT"]=" 4"
D["SIZEOF_LONG"]=" 8"
D["SIZEOF_LONG_LONG"]=" 8"
D["PCMK__CONCURRENT_FENCING_DEFAULT"]=" \"false\""
D["PCMK__SBD_SYNC_DEFAULT"]=" false"
D["PCMK__RESOURCE_STICKINESS_DEFAULT"]=" 0"
D["OCF_ROOT_DIR"]=" \"/usr/lib/ocf\""
D["PACEMAKER_VERSION"]=" \"2.1.4\""
D["PCMK__LOCALE_DIR"]=" \"/usr/share/locale\""
D["PCMK_RUN_DIR"]=" \"/var/run\""
D["PCMK__LSB_INIT_DIR"]=" \"/etc/init.d\""
D["CRM_LOG_DIR"]=" \"/var/log/pacemaker\""
D["CRM_BUNDLE_DIR"]=" \"/var/log/pacemaker/bundles\""
D["PCMK__FENCE_BINDIR"]=" \"/usr/sbin\""
D["OCF_RA_PATH"]=" \"/usr/lib/ocf/resource.d\""
D["PCMK_GNUTLS_PRIORITIES"]=" \"NORMAL\""
D["US_AUTH_PEERCRED_UCRED"]=" 1"
D["SUPPORT_PROCFS"]=" 1"
D["HAVE_DECL_PRIU64"]=" 1"
D["HAVE_DECL_PRIU32"]=" 1"
D["HAVE_DECL_PRIX32"]=" 1"
D["HAVE_DECL_SCNU64"]=" 1"
D["U64T"]=" PRIu64"
D["U32T"]=" PRIu32"
D["X32T"]=" PRIx32"
D["U64TS"]=" SCNu64"
D["VALGRIND_BIN"]=" \"/usr/bin/valgrind\""
D["HAVE_ALPHASORT"]=" 1"
D["HAVE_SCANDIR"]=" 1"
D["HAVE_STRERROR"]=" 1"
D["HAVE_STRCHRNUL"]=" 1"
D["HAVE_STRNLEN"]=" 1"
D["HAVE_STRNDUP"]=" 1"
D["HAVE_LIBDL"]=" 1"
D["HAVE_LIBRT"]=" 1"
D["HAVE_SCHED_SETSCHEDULER"]=" 1"
D["HAVE_NANOSLEEP"]=" 1"
D["HAVE_USLEEP"]=" 1"
D["HAVE_LIBXSLT"]=" 1"
D["HAVE_GETOPT_H"]=" 1"
D["HAVE_LINUX_SWAB_H"]=" 1"
D["HAVE_STDDEF_H"]=" 1"
D["HAVE_SYS_SIGNALFD_H"]=" 1"
D["HAVE_UUID_UUID_H"]=" 1"
D["HAVE_ARPA_INET_H"]=" 1"
D["HAVE_CTYPE_H"]=" 1"
D["HAVE_DIRENT_H"]=" 1"
D["HAVE_ERRNO_H"]=" 1"
D["HAVE_GLIB_H"]=" 1"
D["HAVE_GRP_H"]=" 1"
D["HAVE_LIMITS_H"]=" 1"
D["HAVE_NETDB_H"]=" 1"
D["HAVE_NETINET_IN_H"]=" 1"
D["HAVE_NETINET_IP_H"]=" 1"
D["HAVE_PWD_H"]=" 1"
D["HAVE_SIGNAL_H"]=" 1"
D["HAVE_STDIO_H"]=" 1"
D["HAVE_STDLIB_H"]=" 1"
D["HAVE_STRING_H"]=" 1"
D["HAVE_STRINGS_H"]=" 1"
D["HAVE_SYS_IOCTL_H"]=" 1"
D["HAVE_SYS_PARAM_H"]=" 1"
D["HAVE_SYS_REBOOT_H"]=" 1"
D["HAVE_SYS_RESOURCE_H"]=" 1"
D["HAVE_SYS_SOCKET_H"]=" 1"
D["HAVE_SYS_STAT_H"]=" 1"
D["HAVE_SYS_TIME_H"]=" 1"
D["HAVE_SYS_TYPES_H"]=" 1"
D["HAVE_SYS_UTSNAME_H"]=" 1"
D["HAVE_SYS_WAIT_H"]=" 1"
D["HAVE_TIME_H"]=" 1"
D["HAVE_UNISTD_H"]=" 1"
D["HAVE_LIBXML_XPATH_H"]=" 1"
D["HAVE_LIBXSLT_XSLT_H"]=" 1"
D["HAVE_UUID_UNPARSE"]=" 1"
D["HAVE_DECL_CLOCK_MONOTONIC"]=" 1"
D["HAVE_DECL_ASSERT_FLOAT_EQUAL"]=" 0"
D["HAVE_STRUCT_TM_TM_GMTOFF"]=" 1"
D["HAVE_STRUCT_DIRENT_D_TYPE"]=" 1"
D["SSCANF_HAS_M"]=" 1"
D["HAVE_BZLIB_H"]=" 1"
D["HAVE_LIBBZ2"]=" 1"
D["SUPPORT_PROFILING"]=" 0"
D["CRM_SCHEMA_DIRECTORY"]=" \"/usr/share/pacemaker\""
D["CRM_CORE_DIR"]=" \"/var/lib/pacemaker/cores\""
D["CRM_DAEMON_USER"]=" \"hacluster\""
D["CRM_DAEMON_GROUP"]=" \"haclient\""
D["CRM_PACEMAKER_DIR"]=" \"/var/lib/pacemaker\""
D["CRM_BLACKBOX_DIR"]=" \"/var/lib/pacemaker/blackbox\""
D["PE_STATE_DIR"]=" \"/var/lib/pacemaker/pengine\""
D["CRM_CONFIG_DIR"]=" \"/var/lib/pacemaker/cib\""
D["CRM_DAEMON_DIR"]=" \"/usr/libexec/pacemaker\""
D["CRM_STATE_DIR"]=" \"/var/run/crm\""
D["CRM_RSCTMP_DIR"]=" \"/var/run/resource-agents\""
D["PACEMAKER_CONFIG_DIR"]=" \"/etc/pacemaker\""
D["SBIN_DIR"]=" \"/usr/sbin\""
D["BUILD_VERSION"]=" \"c5ecab892\""
D["SUPPORT_DBUS"]=" 0"
D["SUPPORT_SYSTEMD"]=" 0"
D["SUPPORT_UPSTART"]=" 0"
D["SUPPORT_NAGIOS"]=" 1"
D["NAGIOS_PLUGIN_DIR"]=" \"/usr/libexec/nagios/plugins\""
D["NAGIOS_METADATA_DIR"]=" \"/usr/share/nagios/plugins-metadata\""
D["SUPPORT_COROSYNC"]=" 1"
D["SUPPORT_CIBSECRETS"]=" 0"
D["GCC_FORMAT_NONLITERAL_CHECKING_ENABLED"]=" /**/"
D["CRM_FEATURES"]=" \"corosync-ge-2 monotonic nagios\""
  for (key in D) D_is_set[key] = 1
  FS = ""
}
/^[\t ]*#[\t ]*(define|undef)[\t ]+[_abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ][_abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789]*([\t (]|$)/ {
  line = $ 0
  split(line, arg, " ")
  if (arg[1] == "#") {
    defundef = arg[2]
    mac1 = arg[3]
  } else {
    defundef = substr(arg[1], 2)
    mac1 = arg[2]
  }
  split(mac1, mac2, "(") #)
  macro = mac2[1]
  prefix = substr(line, 1, index(line, defundef) - 1)
  if (D_is_set[macro]) {
    # Preserve the white space surrounding the "#".
    print prefix "define", macro P[macro] D[macro]
    next
  } else {
    # Replace #undef with comments.  This is necessary, for example,
    # in the case of _POSIX_SOURCE, which is predefined and required
    # on some systems where configure will not decide to define it.
    if (defundef == "undef") {
      print "/*", prefix defundef, macro, "*/"
      next
    }
  }
}
{ print }
